#ifndef __caffcc_h
#define __caffcc_h

/*
 * class header for objects (all except primitives)
 */
typedef struct {
    /**
     * Fully qualified domain name of the class, stored as a nul terminated
     * string constant.
     */
    caffc_ptr fqdn; // FIXME: this should a `str` instance

    /**
     * How many fields come after the header that the garbage collector
     * should take care of.
     *
     * NOTE: This is not used in object arrays, arrays have their own field count,
     *       nor in interfaces as they don't have such fields.
     */
    caffc_i32 field_count;

    /**
     * RTTI Inheritance information, for `instanceof`.
     */
    caffc_class_inheritance_data* inheritance_data;
} caffc_class_header;

/**
 * Keeps an array of all the type_ids
 */
typedef struct {
    caffc_u32 count;
    caffc_u32 _inherited_type_ids[];
} caffc_class_inheritance_data;

/*
 * An array generated by the compiler containing the type information of all
 * the classes/interfaces/arrays available in the system. The index it has in
 * this array defines its type_id.
 */
extern caffc_class_header* _caffc_type_ids;

#endif  /* ifndef __caffcc_h */
